# Generated by Django 5.2.6 on 2025-10-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
