# Generated by Django 5.2.6 on 2025-10-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='address',
            field=models.CharField(default='---', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='number',
            name='email',
            field=models.EmailField(default='---', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
