# Generated by Django 5.2.6 on 2025-11-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_number_address_number_email_alter_number_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
